(
// for MKTL
\nanoKONTROL -> (osx: "nanoKONTROL", linux: "nanoKONTROL", protocol: \midi, file: "nanoKONTROL.spec.scd" ),
\Run_N_Drive -> (osx: "Run 'N' Drive", linux: "Thrustmaster Run 'N' Drive", protocol: \hid, file: "Run_N_Drive.spec.scd" ),
\manta: (inport: 1234, outport: 5678, protocol: \osc, file: "Manta.spec.scd" )

);

(
// for Dispatch:
\paged -> ( file: "paged.tpl.scd" )
\speed -> ( file: "speed.tpl.scd" )
\threshold -> ( file: "threshold.tpl.scd" )
);