IdentityDictionary[
\nanoKONTROL -> 
	(osx: ( device: "nanoKONTROL"), linux: ( device: "nanoKONTROL-nanoKONTROL MIDI 1"), protocol: \midi, file: "nanoKONTROL.desc.scd" ),
\Run_N_Drive -> 
	(osx: ( device: "Run'N' Drive"), linux: (device: "Thrustmaster Run\'N\' Drive"), protocol: \hid, file: "Run_N_Drive.desc.scd" ),
\Launchpad -> 
	(osx: ( device: "Launchpad"), linux: (device: "Launchpad"), protocol: \midi, file: "Launchpad.desc.scd" ),
\manta -> 
	(inport: 1234, outport: 5678, protocol: \osc, file: "Manta.desc.scd" )
]